# This is a basic workflow to help you get started with Actions

name: Deploy packages

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:20200407
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Install required dependencies
      run: |
        pacman -Sy --noconfirm s3cmd base-devel devtools wget nettle
        wget https://aur.archlinux.org/cgit/aur.git/snapshot/aurutils.tar.gz

    # - name: Install aurutils
    #   run: |
    #     tar -xf aurutils.tar.gz
    #     chown -R nobody aurutils/
    #     cd aurutils
    #    # allow to sudo as nobody without password
    #     echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    #     mkdir /.gnupg
    #     chown nobody /.gnupg
    #     sudo -u nobody gpg --recv-key DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A
    #     sudo -u nobody makepkg -sci --noconfirm
    #     cd ..
    - name: Build and upload packages
      env: # Or as an environment variable
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
        echo "[default]\naccess_key = $AWS_ACCESS_KEY\nsecret_key = $AWS_SECRET_KEY" > /.s3cfg
        # sudo -u nobody chmod 0600 $HOME/.s3cfg
        echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
        mkdir -p build/arch-repo
        # chown nobody /.s3cfg
        # cat /.s3cfg
        ./bin/build
